### ISSUE TITLE
'Thin::Request processing should close body tempfile when closing' test fails

### ISSUE THREAD

**Issue by voxik** [macournoyer/thin#232]
I observe following error, testing with thin 1.6.2:

```
Failures:
  1) Thin::Request processing should close body tempfile when closing
     Failure/Error: request.body.closed?.should be_true
       expected: true value
            got: false
     # ./spec/request/processing_spec.rb:51:in `block (2 levels) in <top (required)>'
```
