### ISSUE TITLE
Can't restart if no process is running

### ISSUE THREAD

**Issue by Aetherus** [macournoyer/thin#300]
If I run `$ thin start -C config/thin.yml` then `$ thin restart -C config/thin.yml`, everything is fine.

But if there's no thin process running, when I run `$ thin restart -C config/thin.yml`, I got this error:

```
/home/zhoumh/.rvm/gems/ruby-2.3.0/gems/thin-1.6.4/lib/thin/daemonizing.rb:129:in `send_signal': Can't stop process, no PID found in tmp/pids/thin.pid (Thin::PidFileNotFound)
        from /home/zhoumh/.rvm/gems/ruby-2.3.0/gems/thin-1.6.4/lib/thin/daemonizing.rb:117:in `restart'
        from /home/zhoumh/.rvm/gems/ruby-2.3.0/gems/thin-1.6.4/lib/thin/controllers/controller.rb:104:in `block in restart'
        from /home/zhoumh/.rvm/gems/ruby-2.3.0/gems/thin-1.6.4/lib/thin/controllers/controller.rb:135:in `tail_log'
        from /home/zhoumh/.rvm/gems/ruby-2.3.0/gems/thin-1.6.4/lib/thin/controllers/controller.rb:103:in `restart'
        from /home/zhoumh/.rvm/gems/ruby-2.3.0/gems/thin-1.6.4/lib/thin/runner.rb:200:in `run_command'
        from /home/zhoumh/.rvm/gems/ruby-2.3.0/gems/thin-1.6.4/lib/thin/runner.rb:156:in `run!'
        from /home/zhoumh/.rvm/gems/ruby-2.3.0/gems/thin-1.6.4/bin/thin:6:in `<top (required)>'
        from /home/zhoumh/.rvm/gems/ruby-2.3.0/bin/thin:23:in `load'
        from /home/zhoumh/.rvm/gems/ruby-2.3.0/bin/thin:23:in `<main>'
        from /home/zhoumh/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
        from /home/zhoumh/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
```

It's obvious that thin tries to find running processes by reading the pid file and stop them, that's okay. But is it better to just fire up new processes if no old process is running?

Here is my `config/thin.yml`

``` yaml

---
pid: tmp/pids/thin.pid
timeout: 30
wait: 30
log: log/thin.log
max_conns: 1024
require: []
environment: production
max_persistent_conns: 512
servers: 1
threaded: true
no-epoll: false
daemonize: true
port: 3000
tag: origin_delegations
```
